stages:
  - name: eventselection
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        name: recast_sample
        did: {stages: init, output: did, unwrap: true}
        xsec_in_pb: {stages: init, output: xsec_in_pb, unwrap: true}
        dxaod_file: {stages: init, output: dxaod_file, unwrap: true}
        lumi_in_ifb: 30.0
        submitDir: '{workdir}/submitDir'
      step: {$ref: 'steps.yml#/eventselection'}
  - name: statanalysis
    dependencies: [eventselection]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data_file: /code/data/data.root
        signal_file: {stages: eventselection, output: histfile, unwrap: true}
        background_file: /code/data/background.root
        resultdir: '{workdir}/fitresults'
      step: {$ref: 'steps.yml#/statanalysis'}

